/// Generated by https://quicktype.io
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct BlogList {
    #[serde(rename = "posts")]
    pub posts: Vec<Post>,
}

#[derive(Serialize, Deserialize)]
pub struct Post {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "title")]
    pub title: String,

    #[serde(rename = "short")]
    pub short: String,

    #[serde(rename = "filename")]
    pub filename: String,

    #[serde(rename = "author")]
    pub author: String,
}
